### ISSUE TITLE
관광데이터 OPEN API 활용 가이드라인 문서 작성

### ISSUE THREAD

**Issue by sunnyineverywhere** [Snap-Spot/snapspot-api#2]
화요일 정기회의(오후 9시) 이전까지

**Comment by xyzwv** [comment]
<img width="791" alt="image" src="https://github.com/Snap-Spot/snapspot-api/assets/121334671/53f95f74-c749-41a2-afc1-7ae50f2874b4">

[notion 링크](https://sunnyineverywhere.notion.site/627d315346d94aec80b621d760f7382a?pvs=4)

**Comment by rovemin** [comment]
![tourist](https://github.com/Snap-Spot/snapspot-api/assets/97473239/380282f0-5fc4-408b-9bf7-7108d40c9b48)
![course](https://github.com/Snap-Spot/snapspot-api/assets/97473239/32e9a45c-059e-4bb0-abe6-ec392e497bf2)
[notion 링크1](https://www.notion.so/sunnyineverywhere/6c893104511944a2a1cdc6f58f2ffe2a?pvs=4)
[notion 링크2](https://www.notion.so/sunnyineverywhere/f1e2389824e840bcb3b74c9e4a79ecb5?pvs=4)

**Comment by rovemin** [comment]
<img width="791" alt="image" src="https://github.com/Snap-Spot/snapspot-api/assets/97473239/ba42cdad-5ed6-4348-9e49-2e0d83dca601">
<img width="791" alt="image" src="https://github.com/Snap-Spot/snapspot-api/assets/97473239/5edaa69f-ea16-4f78-8e49-834174daea7c">

[notion 링크1](https://www.notion.so/sunnyineverywhere/6c893104511944a2a1cdc6f58f2ffe2a?pvs=4)
[notion 링크2](https://www.notion.so/sunnyineverywhere/f1e2389824e840bcb3b74c9e4a79ecb5?pvs=4)

**Comment by rovemin** [comment]
## 관광객 수 정보 (notion 링크)
<img width="600" alt="image" src="https://github.com/Snap-Spot/snapspot-api/assets/97473239/ba42cdad-5ed6-4348-9e49-2e0d83dca601">

## 코스 및 길 정보 (notion 링크)
<img width="600" alt="image" src="https://github.com/Snap-Spot/snapspot-api/assets/97473239/5edaa69f-ea16-4f78-8e49-834174daea7c">
