### ISSUE TITLE
[QA] 2차

### ISSUE THREAD

**Issue by rovemin** [Snap-Spot/snapspot-api#58]
# Photographer
### 사진 작가 프로필 수정 기능
- [x] 해결
sns 주소 입력 시 에러가 발생합니다.  
지금 sns 컬럼 데이터타입이 모두 VARCHAR(31)로 되어 있는데 예시로 입력 데이터가 "https://blog.naver.com" 인 경우는 api가 정상적으로 작동하지만, "https://blog.naver.com/happysnap" 인 경우 아래와 같은 에러가 발생합니다. 
```
SQL Error: 1406, SQLState: 22001
Data truncation: Data too long for column 'naver_blog' at row 1
```
실제 블로그 주소는 "https://blog.naver.com" 보다 긴 경우가 대부분이어서 수정이 필요합니다.
### 검색어로 사진 작가 목록 조회 기능
응답값이 정상적으로 출력되지 않습니다.
![image](https://github.com/Snap-Spot/snapspot-api/assets/97473239/5592ca5b-3c2b-4c9a-8cef-1e8927776fe7)

# Plan
- [x] 해결
지난번 QA 시 정상적으로 작동했던 기능들이 지금은 message 부분에서 에러가 발생합니다.
### 스냅 사진 촬영 예약 거절 및 취소 기능 & 스냅 사진 촬영 예약 완료 기능 & 스냅 사진 촬영 일정 취소 기능
status는 변경되는데 message가 저장되지 않습니다.
```
SQL Error: 3819, SQLState: HY000
Check constraint 'message_chk_1' is violated.
```
![image](https://github.com/Snap-Spot/snapspot-api/assets/97473239/e3d38553-7d29-47cf-8335-38fe76341d3e)
### 스냅 사진 촬영 비용 입금 요청 기능 
status도 변경되지 않고 request 값도 저장되지 않습니다.
```
SQL Error: 3819, SQLState: HY000
Check constraint 'message_chk_1' is violated.
```
### PlanController 함수명
- [x] 해결
사진 전달 기능 컨트롤러명이 모호합니다. completePlan으로 되어 있는데 사진 전달 Status enum값은 DELIVERY이고, COMPLETE는 촬영 완료의 enum값이어서 혼란의 소지가 있습니다.
@PutMapping("/complete") 이 부분도 마찬가지입니다.

**Comment by sunnyineverywhere** [comment]
@rovemin PlanController에서 `/plan/complete` -> `plan/delivery`로 변경했습니다
놓친 게 진짜 많네요,,, 감사합니다😊
